### Combining data sets

In [2]:
import pandas as pd
import numpy as np

In [3]:
def make_df(cols, ind):
	"""Quickly make a DataFrame"""
	data = {
		c: [str(c) + str(i) for i in ind]
		for c in cols
	}
	return pd.DataFrame(data, ind)

# example DataFrame
make_df("AB", range(3))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [5]:
class display(object):
	"""Display HTML representation of multiple objects"""
	template = """<div style="float: left; padding: 10px;">
	<p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
	</div>"""

	def __init__(self, *args):
		self.args = args

	def _repr_html_(self):
		parts = []
		for a in self.args:
			obj = eval(a)
			html = obj._repr_html_() if hasattr(obj, "_repr_html_") else repr(obj)
			parts.append(self.template.format(a, html))
		return '\n'.join(parts)

	def __repr__(self):
		return '\n\n'.join(a + '\n' + repr(eval(a)) for a in self.args)

### Simple concatenation with pd.concat

In [6]:
ser_1 = pd.Series(['A', 'B', 'C'], index = [1, 2, 3])
ser_2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])
pd.concat([ser_1, ser_2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

In [14]:
df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])
display('df1, df2', "pd.concat([df1, df2], axis='columns')")

df1, df2
(    A   B
1  A1  B1
2  A2  B2,     A   B
3  A3  B3
4  A4  B4)

pd.concat([df1, df2], axis='columns')
     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

## Duplicate indices

In [13]:
x = make_df('AB', [0,1])
y = make_df('AB', [0,1])
display('x', 'y','pd.concat([x, y]) ')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A0  B0
1  A1  B1

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1

In [25]:
 try:
            pd.concat([x, y], verify_integrity=True)
    except ValueError as e:
            print("ValueError", e)
    print("ValueError", e)

IndentationError: unindent does not match any outer indentation level (<string>, line 3)

In [18]:
display('x', 'y', 'pd.concat([x,y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A0  B0
1  A1  B1

pd.concat([x,y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A0  B0
3  A1  B1

In [19]:
display('x', 'y', 'pd.concat([x,y], keys=["x", "y"])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A0  B0
1  A1  B1

pd.concat([x,y], keys=["x", "y"])
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A0  B0
  1  A1  B1

In [26]:
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
display('df5', 'df6', 'pd.concat([df5, df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [27]:
#using inner join
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
display('df5', 'df6', "pd.concat([df5, df6], join='inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [28]:
#using outer join
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
display('df5', 'df6', "pd.concat([df5, df6], join='outer')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='outer')
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [29]:
#using reindex method 
pd.concat([df5, df6.reindex(df5.columns, axis=1)])

     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

### Using pd.join

In [30]:
import pandas as pd
import numpy as np 
class display(object):
	"""Display HTML representation of multiple objects"""
	template = """<div style="float: left; padding: 10px;">
	<p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
	</div>"""

	def __init__(self, *args):
		self.args = args

	def _repr_html_(self):
		parts = []
		for a in self.args:
			obj = eval(a)
			html = obj._repr_html_() if hasattr(obj, "_repr_html_") else repr(obj)
			parts.append(self.template.format(a, html))
		return '\n'.join(parts)

	def __repr__(self):
		return '\n\n'.join(a + '\n' + repr(eval(a)) for a in self.args)

### One to one joins

In [32]:
df1= pd.DataFrame({'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
                    'departments': ['Accounting', 'Engineering', 'Engineering','HR']})
df2= pd.DataFrame({'employee': ['Mercy', 'Mary', 'Mark', 'Maureen'],
                    'hire date': ['2004', '2006', '2008','2010']})
display('df1', 'df2')

df1
  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

df2
  employee hire date
0    Mercy      2004
1     Mary      2006
2     Mark      2008
3  Maureen      2010

In [34]:
df3 = pd.merge(df1,df2)
df3

  employee  departments hire date
0    Mercy   Accounting      2004
1     Mary  Engineering      2006
2     Mark  Engineering      2008
3  Maureen           HR      2010

### Many to one join

In [36]:
', 'HR'],
    'supervisor': ['Melody', 'Mercy', 'Carl', 'Victor']df4 = pd.DataFrame({
    'departments': ['Accounting', 'Engineering', 'Engineering
})
display('df3', 'df4')

df3
  employee  departments hire date
0    Mercy   Accounting      2004
1     Mary  Engineering      2006
2     Mark  Engineering      2008
3  Maureen           HR      2010

df4
   departments supervisor
0   Accounting     Melody
1  Engineering      Mercy
2  Engineering       Carl
3           HR     Victor

In [37]:
df5 = pd.merge(df3,df4)
df5

  employee  departments hire date supervisor
0    Mercy   Accounting      2004     Melody
1     Mary  Engineering      2006      Mercy
2     Mary  Engineering      2006       Carl
3     Mark  Engineering      2008      Mercy
4     Mark  Engineering      2008       Carl
5  Maureen           HR      2010     Victor

### Many to many joins

In [40]:
df6 = pd.DataFrame({
    'departments': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
    'skills': ['math', 'software', 'presentation', 'math', 'communication', 'spreadsheets']
})
display('df4', 'df6', 'pd.merge(df4, df6)')
display('df4','df6','pd.merge(df4,df6)')

df4
   departments supervisor
0   Accounting     Melody
1  Engineering      Mercy
2  Engineering       Carl
3           HR     Victor

df6
   departments         skills
0   Accounting           math
1   Accounting       software
2  Engineering   presentation
3  Engineering           math
4           HR  communication
5           HR   spreadsheets

pd.merge(df4,df6)
   departments supervisor         skills
0   Accounting     Melody           math
1   Accounting     Melody       software
2  Engineering      Mercy   presentation
3  Engineering      Mercy           math
4  Engineering       Carl   presentation
5  Engineering       Carl           math
6           HR     Victor  communication
7           HR     Victor   spreadsheets

In [41]:
display('df1','df2')

df1
  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

df2
  employee hire date
0    Mercy      2004
1     Mary      2006
2     Mark      2008
3  Maureen      2010

In [51]:
display('df1', 'df2', 'pd.merge(df1,df2.on == "employee")')

AttributeError: 'DataFrame' object has no attribute 'on'

AttributeError: 'DataFrame' object has no attribute 'on'

In [44]:
df3 = pd.DataFrame({ 'name': ['Bob','Mercy','Mary','Mark'],
                    'salary':[70000, 10000, 50000, 30000]})

display('df1', 'df3', 'pd.merge(df1, df3, left_on = "employee", right_on = "name")')

df1
  employee  departments
0    Mercy   Accounting
1     Mary  Engineering
2     Mark  Engineering
3  Maureen           HR

df3
    name  salary
0    Bob   70000
1  Mercy   10000
2   Mary   50000
3   Mark   30000

pd.merge(df1, df3, left_on = "employee", right_on = "name")
  employee  departments   name  salary
0    Mercy   Accounting  Mercy   10000
1     Mary  Engineering   Mary   50000
2     Mark  Engineering   Mark   30000

In [46]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop("name", axis=1)

  employee  departments  salary
0    Mercy   Accounting   10000
1     Mary  Engineering   50000
2     Mark  Engineering   30000

In [47]:
df1a = df1.set_index('employee')
df2a = df1.set_index('employee')
display('df1a', 'df2a')

df1a
          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

df2a
          departments
employee
Mercy      Accounting
Mary      Engineering
Mark      Engineering
Maureen            HR

### Read Csv Function

In [9]:
import pandas as pd 
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

display(pop.head(), areas.head(), abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

###  Use how='outer' to make sure no data is thrown away due to mismatched labels

In [ ]:
# many-to-one merge that will give us the full state names within the population DataFrame

merged = pd.merge(pop,abbrevs, how = 'outer', left_on = 'state/region', right_on = 'abbreviation')
merged = merged.drop('abbreviation', axis = 1)
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [ ]:


merged = pd.merge(pop,abbrevs, how = 'outer', left_on = 'state/region', right_on = 'abbreviation')
merged = merged.drop('abbreviation', axis = 1)
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [ ]:
# Looking for rows with nulls

merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [13]:
# looking for null population values 
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [14]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   str
 1   ages          2544 non-null   str
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
 4   state         2448 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 141.1 KB

In [15]:
merged[merged['population'].isnull()].head()

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN

In [16]:
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [17]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

<ArrowStringArray>
['PR', 'USA']
Length: 2, dtype: str

In [18]:
merged.loc[merged['state/region'] == 'PR', 'state' ] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state' ] = 'United States'
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state            0
dtype: int64

In [ ]:
# joining the state column for the areas DataFrame to the merged DataFrame  
display(merged.head(), areas.head())

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [ ]:
# Displaying the final merged DataFrame with the areas DataFrame using a left join on the 'state' column
final_data =pd.merge(merged, areas, on = 'state', how = 'left')
final_data.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [22]:
# checking for null values in the final_data DataFrame
final_data.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [23]:
final_data.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [24]:
# dropping null values because united states is not in the areas DataFrame
final_data.dropna(inplace = True)
final_data.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [25]:
# looking if there is still null data 
final_data.isnull().any()

state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool

In [26]:
data2010 = final_data.query("year == 2010 & ages == 'total'")
data2010.head()

    state/region   ages  year  population       state  area (sq. mi)
43            AK  total  2010    713868.0      Alaska       656425.0
51            AL  total  2010   4785570.0     Alabama        52423.0
141           AR  total  2010   2922280.0    Arkansas        53182.0
149           AZ  total  2010   6408790.0     Arizona       114006.0
197           CA  total  2010  37333601.0  California       163707.0

In [27]:
# Computing population density and displaying in order
# Reindexing the data2010 DataFrame by the 'state' column to facilitate density calculation
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']

In [ ]:
# sort values to see the start of the list
density.sort_values(ascending=False, inplace=True)
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [29]:
# sort values so we can see end of the list 
density.tail()

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64